name: Video Generation
on:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes
        uses: manim-kindergarten/manim_action_renderer@master
        id: renderer
        with:
          source_file: useful_vote.py
          args: "--high_quality"
          extra_system_packages: pango-dev
          extra_packages: manim-voiceover numpy
      - name: Save output as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Videos
          path: ${{ steps.renderer.outputs.video_path }}
